CREATE DATABASE IF NOT EXISTS `authn_db`;
ALTER SCHEMA `authn_db`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_bin ;
GRANT ALL PRIVILEGES ON *.* TO 'app_user'@'%' IDENTIFIED BY 'Password4' WITH GRANT OPTION;
USE `authn_db`;